app:
  gzip: true
  key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
  name: ktmall
  port: :9999
  public_dir: public
  resources_dir: resources
  runmode: development
  temp_dir: storage
  template_dir: resources/views
  upload_dir: public/uploads
  url: http://localhost:9999
db:
  auto_migrate: true
  connection: mysql
  database: ktmall
  host: 127.0.0.1
  max_idle_connections: 20
  max_open_connections: 100
  options: charset=utf8&parseTime=true&loc=Local
  password: 1234
  port: 3306
  username: root
log:
  log_backup_count: 7
  log_format_text: false
  log_rotate_date: 1
  log_rotate_size: 1
  logger_file: storage/logs/2019_11_18.log
  logger_level: DEBUG
  rolling_policy: size
  writers: file,stdout
qiniu:
  access_key: izaWwC7D_YgKgKAlJnUZLysQXUQn5x4DDNKi0Tt5
  secret_key: 3G4uVk3D-8_lIBbNaF9_HPSlVd_u-BnnAKIumMoD
