APP:
  NAME: ktmall
  RUNMODE: development # 模式: development, production, staging, test
  PORT: :9999 # 端口
  URL: http://localhost:9999 # 网站地址
  KEY: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: ktmall # DB.DATABASE_APP.RUNMODE: ktmall_development
  USERNAME: root
  PASSWORD: 1234

# 七牛云配置
QINIU:
  ACCESS_KEY:
  SECRET_KEY:

# alipay
ALIPAY:
  APPID:

# 极光推送
JPUSH:
  KEY:
  SECRET:
