APP:
  NAME: ktmall
  RUNMODE: development # 模式: development, production, staging, test
  PORT: :9999 # 端口
  URL: http://localhost:9999 # 网站地址
  KEY: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: ktmall # DB.DATABASE_APP.RUNMODE: ktmall_development
  USERNAME: root
  PASSWORD: 1234

# 七牛云配置
QINIU:
  ACCESS_KEY: izaWwC7D_YgKgKAlJnUZLysQXUQn5x4DDNKi0Tt5
  SECRET_KEY: 3G4uVk3D-8_lIBbNaF9_HPSlVd_u-BnnAKIumMoD

# alipay
ALIPAY:
  APPID: 2016101500688886
